"""Add FAQ and PackageEnhancement tables

Revision ID: 100db6586cb8
Revises: 5aaea3cf48ca
Create Date: 2025-10-30 19:00:55.528020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100db6586cb8'
down_revision: Union[str, Sequence[str], None] = '5aaea3cf48ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
