"""Add agent handoff fields to sessions

Revision ID: 5aaea3cf48ca
Revises: 587cc1f23d54
Create Date: 2025-10-29 20:44:56.351081

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5aaea3cf48ca"
down_revision: Union[str, Sequence[str], None] = "587cc1f23d54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires server_default for NOT NULL columns
    op.add_column(
        "sessions",
        sa.Column(
            "is_handled_by_agent", sa.Boolean(), nullable=False, server_default="1"
        ),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "transferred_to_human", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    op.add_column("sessions", sa.Column("transfer_reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "transfer_reason")
    op.drop_column("sessions", "transferred_to_human")
    op.drop_column("sessions", "is_handled_by_agent")
    # ### end Alembic commands ###
