"""Add gallery_images column to gallery_items

Revision ID: 5d9a0c5c193b
Revises: d929392b417f
Create Date: 2025-11-07 11:43:31.270644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d9a0c5c193b"
down_revision: Union[str, Sequence[str], None] = "d929392b417f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gallery_items", sa.Column("gallery_images", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gallery_items", "gallery_images")
    # ### end Alembic commands ###
